[Feature/userlist] 유저리스트를 불러오는 기능
where-we-meet/owl pull request #25
Opened 2024-04-02 12:46 UTC by gidalim

## 📌 관련 이슈

 #17 
## Task TODOLIST

- [x] 데이터 테이블을 조인하여 가져오는 로직
- [x] 가져온 데이터를 어드민, 현재로그인유저, 그 외 유저로 정렬하는 로직

## ✨ 개발 내용

```
현재 방의 정보인 userdata_room 테이블과, users 테이블을 조인하여 정보를 가져왔습니다.
```
##  TroubleShotting

```
현재 타입에서 유저의 정보를 추론할 수 없기 때문에 as [ ]를 이용하여 오류를 회피했습니다.
```
## 📸 스크린샷(선택)
![image](https://github.com/where-we-meet/owl/assets/109938441/69dcad45-2464-4186-ba22-b17d4046ec94)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

데이터 테이블이 변했다면, supabase에서 새로운 타입을 최신화 시켜주세요!
## 테스트케이스

없음!

2024-04-02 16:36 UTC, heechul94 approved these changes
👍 LGTM

2024-04-02 16:38 UTC, lauichan requested changes

2024-04-02 16:38 UTC, lauichan commented on .eslintrc.json
> +  }
`<img>` 경고 무시하는거 요렇게 추가하는 군요

2024-04-02 16:38 UTC, lauichan commented on src/components/room/sidebar/user/UserList.tsx
> +      const sortedUsers = [...adminUser, ...currentUser, ...otherUsers];
`const sortedUsers: Users[] = [...adminUser, ...currentUser, ...otherUsers];`

30번째 줄에 `as []` 하는 것보다 저렇게 바꾸는게 좋을 것 같아요

2024-04-03 03:50 UTC, gidalim commented on .eslintrc.json
> +  }
네!

2024-04-03 03:50 UTC, gidalim commented on src/components/room/sidebar/user/UserList.tsx
> +      const sortedUsers = [...adminUser, ...currentUser, ...otherUsers];
확인했습니다!

2024-04-03 03:50 UTC, ketchup0211 approved these changes
LGTM!

2024-04-03 03:51 UTC, lauichan approved these changes
수고하셨씁니다

2024-04-03 03:51 UTC, merged